### ISSUE TITLE
[BEHAVIOR DIFFERENCE]: varlist don't have the same amount of console variables

### ISSUE THREAD

**Issue by NexiusTailer** [openmultiplayer/server-beta-old#178]
# Description

OMP server lacks some of the console variables comparing to SA-MP server when the user tries to check all them in a list by calling `varlist` console command. This would probably be because omp server start reading a legacy-config file in my case so that some values could be missed in it, but they still should be displayed with their default values in a list.

They are (which missed in varlist but can be detected by deprecation warnings):
- `bool` logging.log_chat (`int` chatlogging in samp)
- `bool` logging.log_cookies (`int` cookielogging in samp)
- `bool` logging.log_sqlite_queries (`int` db_log_queries in samp)
- `bool` logging.log_sqlite (`int` db_logging in samp)
- `string` pawn.side_scripts (`string` filterscripts in samp)
- `bool` game.use_lag_compensation (`int` lagcompmode in samp)
- `bool` network.use_lan_mode (`int` lagcompmode in samp)
- `bool` logging.log_queries (`int` logqueries in samp)
- `bool` enable_query (`bool` query in samp)
- `bool` rcon.enable (`bool` rcon in samp)
- `bool` logging.use_timestamp (`bool` timestamp in samp)

Other ones (they even not shown by warnings when using old samp names):
- `int` game.time ? (using `string` worldtime from samp)
- `string` pawn.main_scripts ? (using `string` gamemode0 - gamemode15 from samp)
- merged into `bool` game.use_lag_compensation ? (using `string` lagcomp from samp)
- ??? (using `int` conncookies from samp)
- ??? (using `int` queryflood from samp)

There's also at least one variable which is not missed, but its name has typo in `varlist` only:
- network.message_hole**s**_limit (should be network.message_hole_limit)

# How to re-produce this behavior difference

Start both servers one by one and type `varlist` command.

Test script to invoke all variables with old samp names (mainly to see the warnings, ensure their current names and also ensure that the omp server consider them and know about their existence at all):
```pawn
public OnGameModeInit()
{
	new test[32];
	GetConsoleVarAsInt("ackslimit");
	GetConsoleVarAsBool("announce");
	GetConsoleVarAsString("bind", test, sizeof test);
	GetConsoleVarAsInt("chatlogging");
	GetConsoleVarAsInt("conncookies");
	GetConsoleVarAsInt("connseedtime");
	GetConsoleVarAsInt("cookielogging");
	GetConsoleVarAsInt("db_log_queries");
	GetConsoleVarAsInt("db_logging");
	GetConsoleVarAsString("filterscripts", test, sizeof test);
	GetConsoleVarAsString("gamemode0", test, sizeof test);
	GetConsoleVarAsString("gamemode1", test, sizeof test);
	GetConsoleVarAsString("gamemode2", test, sizeof test);
	GetConsoleVarAsString("gamemode3", test, sizeof test);
	GetConsoleVarAsString("gamemode4", test, sizeof test);
	GetConsoleVarAsString("gamemode5", test, sizeof test);
	GetConsoleVarAsString("gamemode6", test, sizeof test);
	GetConsoleVarAsString("gamemode7", test, sizeof test);
	GetConsoleVarAsString("gamemode8", test, sizeof test);
	GetConsoleVarAsString("gamemode9", test, sizeof test);
	GetConsoleVarAsString("gamemode10", test, sizeof test);
	GetConsoleVarAsString("gamemode11", test, sizeof test);
	GetConsoleVarAsString("gamemode12", test, sizeof test);
	GetConsoleVarAsString("gamemode13", test, sizeof test);
	GetConsoleVarAsString("gamemode14", test, sizeof test);
	GetConsoleVarAsString("gamemode15", test, sizeof test);
	GetConsoleVarAsString("gamemodetext", test, sizeof test);
	GetConsoleVarAsString("gravity", test, sizeof test);
	GetConsoleVarAsString("hostname", test, sizeof test);
	GetConsoleVarAsInt("incar_rate");
	GetConsoleVarAsString("lagcomp", test, sizeof test);
	GetConsoleVarAsInt("lagcompmode");
	GetConsoleVarAsString("language", test, sizeof test);
	GetConsoleVarAsBool("lanmode");
	GetConsoleVarAsBool("logqueries");
	GetConsoleVarAsString("logtimeformat", test, sizeof test);
	GetConsoleVarAsString("mapname", test, sizeof test);
	GetConsoleVarAsInt("maxnpc");
	GetConsoleVarAsInt("maxplayers");
	GetConsoleVarAsInt("messageholelimit");
	GetConsoleVarAsInt("messageslimit");
	GetConsoleVarAsInt("minconnectiontime");
	GetConsoleVarAsBool("myriad");
	GetConsoleVarAsString("nosign", test, sizeof test);
	GetConsoleVarAsInt("onfoot_rate");
	GetConsoleVarAsString("password", test, sizeof test);
	GetConsoleVarAsInt("playertimeout");
	GetConsoleVarAsString("plugins", test, sizeof test);
	GetConsoleVarAsInt("port");
	GetConsoleVarAsBool("query");
	GetConsoleVarAsInt("queryflood");
	GetConsoleVarAsBool("rcon");
	GetConsoleVarAsString("rcon_password", test, sizeof test);
	GetConsoleVarAsInt("sleep");
	//GetConsoleVarAsString("stream_distance", test, sizeof test);
	GetConsoleVarAsInt("stream_rate");
	GetConsoleVarAsBool("timestamp");
	GetConsoleVarAsString("version", test, sizeof test);
	GetConsoleVarAsInt("weapon_rate");
	GetConsoleVarAsString("weather", test, sizeof test);
	GetConsoleVarAsString("weburl", test, sizeof test);
	GetConsoleVarAsString("worldtime", test, sizeof test);
	return 1;
}
```

# Relevant log output

SA-MP server
```
[18:03:47] Console Variables:
[18:03:47]   ackslimit	= 3000  (int)
[18:03:47]   announce	= 1  (bool)
[18:03:47]   bind		= ""  (string) (read-only)
[18:03:47]   chatlogging	= 0  (int)
[18:03:47]   conncookies	= 1  (int)
[18:03:47]   connseedtime	= 300000  (int)
[18:03:47]   cookielogging	= 0  (int)
[18:03:47]   db_log_queries	= 0  (int)
[18:03:47]   db_logging	= 0  (int)
[18:03:47]   filterscripts	= ""  (string) (read-only)
[18:03:47]   gamemode0	= "test"  (string)
[18:03:47]   gamemode1	= ""  (string)
[18:03:47]   gamemode10	= ""  (string)
[18:03:47]   gamemode11	= ""  (string)
[18:03:47]   gamemode12	= ""  (string)
[18:03:47]   gamemode13	= ""  (string)
[18:03:47]   gamemode14	= ""  (string)
[18:03:47]   gamemode15	= ""  (string)
[18:03:47]   gamemode2	= ""  (string)
[18:03:47]   gamemode3	= ""  (string)
[18:03:47]   gamemode4	= ""  (string)
[18:03:47]   gamemode5	= ""  (string)
[18:03:47]   gamemode6	= ""  (string)
[18:03:47]   gamemode7	= ""  (string)
[18:03:47]   gamemode8	= ""  (string)
[18:03:47]   gamemode9	= ""  (string)
[18:03:47]   gamemodetext	= "Unknown"  (string)
[18:03:47]   gravity	= "0.008"  (string)
[18:03:47]   hostname	= "SA-MP 0.3 Server"  (string)
[18:03:47]   incar_rate	= 40  (int) (read-only)
[18:03:47]   lagcomp	= "On"  (string) (read-only) (rule)
[18:03:47]   lagcompmode	= 1  (int) (read-only)
[18:03:47]   language	= "Russian"  (string)
[18:03:47]   lanmode	= 0  (bool)
[18:03:47]   logqueries	= 0  (bool)
[18:03:47]   logtimeformat	= "[%H:%M:%S]"  (string) (read-only)
[18:03:47]   mapname	= "San Andreas"  (string) (rule)
[18:03:47]   maxnpc	= 80  (int)
[18:03:47]   maxplayers	= 80  (int) (read-only)
[18:03:47]   messageholelimit	= 3000  (int)
[18:03:47]   messageslimit	= 500  (int)
[18:03:47]   minconnectiontime	= 0  (int)
[18:03:47]   myriad	= 0  (bool)
[18:03:47]   nosign	= ""  (string) (read-only)
[18:03:47]   onfoot_rate	= 40  (int) (read-only)
[18:03:47]   password	= ""  (string)
[18:03:47]   playertimeout	= 10000  (int)
[18:03:47]   plugins	= "crashdetect"  (string) (read-only)
[18:03:47]   port		= 7777  (int) (read-only)
[18:03:47]   query		= 1  (bool)
[18:03:47]   queryflood	= 1  (int)
[18:03:47]   rcon		= 0  (bool)
[18:03:47]   rcon_password	= "12345"  (string)
[18:03:47]   sleep		= 5  (int)
[18:03:47]   stream_distance	= 300.000000  (float)
[18:03:47]   stream_rate	= 1000  (int)
[18:03:47]   timestamp	= 1  (bool)
[18:03:47]   version	= "0.3.7-R3"  (string) (read-only) (rule)
[18:03:47]   weapon_rate	= 40  (int) (read-only)
[18:03:47]   weather	= "10"  (string) (rule)
[18:03:47]   weburl	= "www.sa-mp.com"  (string) (rule)
[18:03:47]   worldtime	= "12:00"  (string) (rule)
```

OMP server
```
[18:04:16] [Info] Console variables:
[18:04:16] [Info] bind = "" (string)
[18:04:16] [Info] bot_exe = "samp-npc" (string)
[18:04:16] [Info] game.chat_radius = 200.000000 (float)
[18:04:16] [Info] game.death_drop_amount = 0 (int)
[18:04:16] [Info] game.gravity = 0.008000 (float)
[18:04:16] [Info] game.map = "" (string)
[18:04:16] [Info] game.mode = "" (string)
[18:04:16] [Info] game.nametag_draw_radius = 70.000000 (float)
[18:04:16] [Info] game.player_marker_draw_radius = 250.000000 (float)
[18:04:16] [Info] game.player_marker_mode = 1 (int)
[18:04:16] [Info] game.time = 12 (int)
[18:04:16] [Info] game.vehicle_respawn_time = 10000 (int)
[18:04:16] [Info] game.weather = 10 (int)
[18:04:16] [Info] language = "Russian" (string)
[18:04:16] [Info] logging.timestamp_format = "[%H:%M:%S]" (string)
[18:04:16] [Info] max_bots = 80 (int)
[18:04:16] [Info] max_players = 80 (int)
[18:04:16] [Info] name = "SA-MP 0.3 Server" (string)
[18:04:16] [Info] network.acks_limit = 3000 (int)
[18:04:16] [Info] network.aiming_sync_rate = 40 (int)
[18:04:16] [Info] network.cookie_reseed_time = 300000 (int)
[18:04:16] [Info] network.in_vehicle_sync_rate = 40 (int)
[18:04:16] [Info] network.limits_ban_time = 60000 (int)
[18:04:16] [Info] network.message_holes_limit = 3000 (int)
[18:04:16] [Info] network.messages_limit = 500 (int)
[18:04:16] [Info] network.minimum_connection_time = 0 (int)
[18:04:16] [Info] network.mtu = 576 (int)
[18:04:16] [Info] network.multiplier = 10 (int)
[18:04:16] [Info] network.on_foot_sync_rate = 40 (int)
[18:04:16] [Info] network.player_marker_sync_rate = 2500 (int)
[18:04:16] [Info] network.player_timeout = 10000 (int)
[18:04:16] [Info] network.stream_radius = 300.000000 (float)
[18:04:16] [Info] network.stream_rate = 1000 (int)
[18:04:16] [Info] network.time_sync_rate = 30000 (int)
[18:04:16] [Info] password = "" (string)
[18:04:16] [Info] pawn.legacy_plugins = "crashdetect streamer CRP pawnraknet" (strings)
[18:04:16] [Info] pawn.main_scripts = "test" (strings)
[18:04:16] [Info] port = 7777 (int)
[18:04:16] [Info] rcon.password = "12345" (string)
[18:04:16] [Info] sleep = 5 (int)
[18:04:16] [Info] version = "open.mp 0.0.8.1988" (string)
[18:04:16] [Info] website = "www.sa-mp.com" (string)
```

# open.mp server version

[Build 8](https://github.com/openmultiplayer/server-beta/releases/tag/build8)

# Operating system or distribution

Windows 10 (21H2)

# Contact information

Nexius#2253

**Comment by ksenonadv** [comment]
Fixed in build9.

**Comment by NexiusTailer** [comment]
The following parts of the issue are still relevant on the latest build:
- `string` pawn.side_scripts (`string` filterscripts in samp) missed in varlist but can be detected by deprecation warnings
- using `string` worldtime in GetConsoleVarAsString does not produce a warning with relevant name for this deprecated variable
- using `string` gamemode0 - gamemode15 in GetConsoleVarAsString does not produce a warning with relevant name for this deprecated variable
- using `string` lagcomp in GetConsoleVarAsString does not produce a warning with relevant name for this deprecated variable
- using `int` conncookies in GetConsoleVarAsInt does not produce a warning with relevant name for this deprecated variable
- using `int` queryflood in GetConsoleVarAsInt does not produce a warning with relevant name for this deprecated variable

One more tiny difference is that now bool parameters have `(boolean)` uncut tag name in omp varlist, but `(bool)` tag name in samp varlist.
